"use client";

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "../globals.css";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: {
//     default: "Dashboard - Learning Next.js",
//     template: "%s | Dashboard - Learning Next.js",
//   },
//   description: "Generated by create next app",
// };

// normally we are using that nav in header component
const nav = [
  { href: "/", label: "Home" },
  { href: "/products", label: "Products" },
  { href: "/about", label: "About" },
  { href: "/feature", label: "Feature" },
  { href: "/docs", label: "Documents" },
  { href: "/login", label: "Login" },
  { href: "/register", label: "Register" },
  { href: "/complex-dashboard", label: "Complex Dashboard" },
];

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <div className="py-4 bg-amber-900">Header</div>
        <div className="flex gap-4 p-4">
          {nav.map((link) => {
            const isActive =
              pathname === link.href ||
              (pathname.startsWith(link.href) && link.href !== "/");
            return (
              <div key={link.href}>
                <Link
                  className={isActive ? "text-blue-500" : ""}
                  href={link.href}
                >
                  {link.label}
                </Link>
              </div>
            );
          })}
        </div>
        {children}
        <div className="py-4 bg-amber-900 mt-auto">Footer</div>
      </body>
    </html>
  );
}
