export const errorCode = {
  invalid: "Error_Invalid",
  unauthenticated: "Error_Unauthenticated",
  attack: "Error_Attack",
  accessTokenExpired: "Error_AccessTokenExpired",
  userExist: "Error_UserAlreadyExist",
  phoneExist: "Error_PhoneNumberAlreadyExist",
  overLimit: "Error_OverLimit",
  otpExpired: "Error_OtpExpired",
  requestExpired: "Error_RequestExpired",
  accountFreeze: "Error_AccountFreeze",
  unauthorized: "Error_Unauthorized",
  maintenance: "Error_Maintenance",
  notFound: "Error_NotFound",
};
